config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: 'users' do
    resources :users, :path => 'u', :only => [:index, :show, :destroy]
  end

  def post_resource
    resources :forum_posts, :path => 'p', :as => 'posts'
  end

  scope module: 'forums' do
    resources :forum_threads, :path => 'forums', :as => 'threads' do
      post_resource
    end
    resources :forum_posts, :path => 'forums/p', :as => 'posts', :only => [] do
      member do
        post 'vote'
      end
      post_resource
    end
    resources :officials, :path => 'matches', :as => 'matches', :only => [] do
      post_resource
    end
    resources :news, :path => 'news', :as => 'news', :only => [] do
      post_resource
    end
  end

  scope module: 'news' do
    resources :news, :path => 'news', :as => 'news'
  end

  scope module: 'officials' do
    resources :events do
      resources :sections, :path => 's', :except => [:index]
    end
    resources :rankings, :only => [:index]
    resources :officials, :path => 'matches', :as => 'matches', :except => [:edit] do
      resources :maps, :only => [:create, :update, :destroy]
    end
    resources :teams
    resources :players
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
end

app/models/forum/forum_post.rb
class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :forum_posts, as: :commentable
  has_many :votes, as: :votable, dependent: :destroy
  after_create -> (x) {update_count(1)}
  before_destroy -> (x) {update_count(-1)}
  validates :body, presence: true

  def update_count(num)
    parent = ForumPost.find_parent(self)
    parent.comments_count += num
    parent.save!
  end

  def self.find_parent(child)
    parent = child.commentable
    while parent.is_a? ForumPost
      parent = parent.commentable
    end
    return parent
  end
end

app/models/forum/forum_thread.rb
include ActionView::Helpers::DateHelper

class ForumThread < ApplicationRecord
  belongs_to :user
  has_many :forum_posts, as: :commentable,  dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  validates :subject, presence: true
  validates :description, presence: true
end

app/controllers/forums/forum_posts_controller.rb
class Forums::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, except: [:update, :destroy]
  before_action :set_post, only: [:update, :destroy]

  def create
    @post = @commentable.forum_posts.new(forum_post_params)
    authorize @post
    @post.user = current_user
    if @post.save
      flash[:success] = "Post successfully created."
    else
      flash[:danger] = @post.errors.full_messages
    end
    redirect_to find_parent_route?(@post)
  end

  def update
    authorize @post
    @post.body = forum_post_params[:body]
    if @post.save
      flash[:success] = "Post successfully edited."
    else
      flash[:danger] = @post.errors.full_messages
    end
    redirect_to find_parent_route?(@post)
  end

  def destroy
    authorize @post
    route = find_parent_route?(@post)
    @post.destroy
    flash[:success] = "Post successfully deleted."
    redirect_to route
  end

  def vote
    @prev_vote = @forumpost.votes.where(user_id: current_user.id)
    if @prev_vote.any?
      @prev_vote.destroy_all
    end

    @vote = @forumpost.votes.new(direction: params[:direction])
    @vote.user = current_user
    @vote.save

    respond_to do |format|
      format.js
    end
  end

  private
    def find_commentable
      if params[:post_id]
        @commentable = ForumPost.find(params[:post_id])
      elsif params[:thread_id]
        @commentable = ForumThread.find(params[:thread_id])
      elsif params[:match_id]
        @commentable = Official.find(params[:match_id])
      elsif params[:news_id]
        @commentable = New.find(params[:news_id])
      else
        @forumpost = ForumPost.find(params[:id])
      end
    end

    def find_parent_route?(child)
      parent = ForumPost.find_parent(child)
      type = parent.class

      if type == ForumThread
        return thread_path(parent)
      elsif type == Official
        return match_path(parent)
      elsif type == New
        return news_path(parent)
      end
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end

    def set_post
      @post = ForumPost.find(params[:id])
    end
end

app/controllers/forums/forum_threads_controller.rb
require 'will_paginate/array'

class Forums::ForumThreadsController < ApplicationController
  skip_before_action :get_discs, except: [:show]
  before_action :disable_discs, except: [:show]
  before_action :authenticate_user!, only: [:create]
  before_action :set_forum_thread, except: [:index, :new, :create]

  def index
    @forum_thread = ForumThread.new

    if params[:f] == "threads"
      @discs = ForumThread.order(updated_at: :desc).includes(:user).paginate(:page => params[:page], :per_page => 20)
    elsif params[:f] == "news"
      @discs = New.order(updated_at: :desc).includes(:user).paginate(:page => params[:page], :per_page => 20)
      @new = New.new
    elsif params[:f] == "matches"
      @discs = Official.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 20)
    else
      @threads_sb = ForumThread.order(updated_at: :desc).includes(:user)
      @matches_sb = Official.order(updated_at: :desc)
      @news_sb = New.order(updated_at: :desc).includes(:user)
      @discs = (@threads_sb + @matches_sb + @news_sb).sort_by(&:updated_at).reverse.paginate(:page => params[:page], :per_page => 20)
    end

  end

  def show

  end

  def create
    @forum_thread = ForumThread.new(forum_thread_params)
    authorize @forum_thread
    @forum_thread.user = current_user

    if @forum_thread.save
      flash[:success] = "Thread successfully created"
      redirect_to thread_path(@forum_thread)
    else
      flash[:danger] = @forum_thread.errors.full_messages
      redirect_to threads_path
    end
  end

  def update
    authorize @forum_thread
    if @forum_thread.update_attributes(forum_thread_params)
      flash[:success] = "Successfully updated Forum Thread"
    else
      flash[:danger] = "Unable to update Forum Thread. There is an error with a field."
    end
    redirect_to thread_path(@forum_thread)
  end

  def destroy
    authorize @forum_thread
    @forum_thread.destroy
    flash[:success] = "Thread successfully deleted."
    redirect_to threads_path
  end

  private
    def disable_discs
      @disable_1 = true
    end

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, :description)
    end
end

app/views/forums/forum_threads/index.html.erb
<div class="column-2">
  <div class="descriptor">
    <span><%= link_to "All", threads_path %></span>
    <span><%= link_to "News", threads_path(:f => "news")%></span>
    <span><%= link_to "Matches", threads_path(:f => "matches")%></span>
    <span><%= link_to "Discussions", threads_path(:f => "threads")%></span>
  </div>
  <div class="forum-index">
    <div class="forum-index-header">
      <div>Topic</div>
      <div class="mobile-dismiss">Author</div>
      <div>Activity</div>
      <div>Comments</div>
    </div>
    <% @discs.each do |thread| %>
      <%= react_component("Thread", {thread: thread, compact: true, author: get_author(thread), path: disc_path?(thread)}) %>
    <% end %>
  </div>

  <div class="pagination">
    <div class="page_info">
      <%= page_entries_info @discs %>
    </div>
    <%= will_paginate @discs, :container => false, :inner_window => 1, :outer_window => 1 %>
  </div>
  <% if user_signed_in? && params[:f] != "news" && params[:f] != "matches" %>
    <div class="descriptor">Create New Thread</div>
    <div class="admin-form shadow-sm">
      <%= form_for(@forum_thread, url: threads_path) do |f| %>
        <div class='fields'>
          <div>
            <div class="descriptor">Title</div>
            <%= f.text_field :subject%>
          </div>
          <div>
            <div class="descriptor">Content</div>
            <%= f.cktext_area :description, ckeditor: {toolbar: "mini", height: 300, toolbarCanCollapse: true}%>
          </div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if params[:f] == "news" && policy(@new).create? %>
    <div class="descriptor">Create News Article</div>
    <div class="admin-form shadow-sm">
      <%= form_for(@new, url: news_index_path) do |f| %>
        <div class="fields">
          <div>
            <div class='descriptor'>Title</div>
            <%= f.text_field :subject%>
          </div>
          <div>
            <div class='descriptor'>Content</div>
            <%= f.cktext_area :article, ckeditor: {height: 300, toolbarCanCollapse: true}%>
          </div>
          <div>
              <div class="descriptor">Featured</div>
              <%= f.check_box :featured %>
          </div>
          <div>
            <div class="descriptor">Logo</div>
            <div class="edit-avatar">
              <div><%= f.file_field :avatar%></div>
            </div>
          </div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="column-4">
  <%= render "layouts/matches", :upcoming => @upcoming, :completed => @completed %>
</div>

app/views/forums/forum_threads/show.html.erb
<div class="column-2">
  <div class="thread">
    <div class="descriptor">
      <%= link_to "Forums", threads_path %> >
      <%= link_to "Discussions", threads_path(:f => "threads")%> >
      <span><%=@forum_thread.subject%></span>
    </div>
    <%= react_component("Thread", {timestamp: get_time_ago(@forum_thread.created_at), thread: @forum_thread, user: @forum_thread.user, compact: false}) %>
    <div class="descriptor">Comments</div>
    <%= render(partial: 'forums/forum_posts/post', collection: @forum_thread.forum_posts.includes(:user)) %>
    <hr>
    <div class="post-reply bottom-reply">
      <% if user_signed_in? %>
        <%= form_for(ForumPost.new, url: thread_posts_path(@forum_thread)) do |f| %>
          <%= f.cktext_area :body, ckeditor: {toolbar: "mini", height: 200, toolbarCanCollapse: true}, class: "ckeditor"%>
          <%= f.submit "Submit Post", class: "submit-post-button" %>
        <% end %>
      <% else %>
        Login or register to add your comment to the discussion.
      <% end %>
    </div>
    <% if policy(@forum_thread).destroy? %>
      <div class="descriptor">Moderator Actions</div>
      <div class="admin-actions">
        <div>
          <%= link_to 'Delete Thread', thread_path(@forum_thread), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'Edit Thread', 'javascript:;', class: "admin-panel 1" %>
        </div>
        <div id="panel-1" class="admin-form hidden">
          <%= form_for(@forum_thread, url: thread_path(@forum_thread), method: :patch) do |f| %>
            <div class='fields'>
              <div>
                <div class="descriptor">Title</div>
                <%= f.text_field :subject, :value => @forum_thread.subject %>
              </div>
              <div>
                <div class="descriptor">Content</div>
                <%= f.cktext_area :description, value: @forum_thread.description, ckeditor: {toolbar: "mini", height: 300, toolbarCanCollapse: true}%>
              </div>
              <%= f.submit "Submit" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="column-4">
  <%= render "layouts/matches", :upcoming => @upcoming, :completed => @completed %>
</div>