config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: 'users' do
    resources :users, :path => 'u', :only => [:index, :show, :destroy]
  end

  def post_resource
    resources :forum_posts, :path => 'p', :as => 'posts'
  end

  scope module: 'forums' do
    resources :forum_threads, :path => 'forums', :as => 'threads' do
      post_resource
    end
    resources :forum_posts, :path => 'forums/p', :as => 'posts', :only => [] do
      member do
        post 'vote'
      end
      post_resource
    end
    resources :officials, :path => 'matches', :as => 'matches', :only => [] do
      post_resource
    end
    resources :news, :path => 'news', :as => 'news', :only => [] do
      post_resource
    end
  end

  scope module: 'news' do
    resources :news, :path => 'news', :as => 'news'
  end

  scope module: 'officials' do
    resources :events do
      resources :sections, :path => 's', :except => [:index]
    end
    resources :rankings, :only => [:index]
    resources :officials, :path => 'matches', :as => 'matches', :except => [:edit] do
      resources :maps, :only => [:create, :update, :destroy]
    end
    resources :teams
    resources :players
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
end

app/models/new.rb
class New < ApplicationRecord
  has_one_attached :avatar
  mount_uploaders :pictures, CkeditorPictureUploader
  serialize :pictures, JSON
  belongs_to :user
  has_many :forum_posts, as: :commentable
  validates :subject, presence: true
end

app/controllers/news/news_controller.rb
class News::NewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_new, only: [:show, :update, :destroy]
  before_action :news_params, except: [:show, :destroy]

  def show
    @post = ForumPost.new
  end

  def create
    @article = New.new(news_params)
    @article.user = current_user

    if @article.save
      flash[:success] = "Article successfully created"
      redirect_to @article
    else
      flash[:danger] = @article.errors.full_messages
      redirect_to threads_path(:f => "news")
    end
  end

  def update
    authorize @news
    if @news.update_attributes(news_params)
      flash[:success] = "Successfully updated news article"
    else
      flash[:danger] = "Unable to update news article"
    end
    redirect_to news_path(@news)
  end

  def destroy
    authorize @news
    flash[:success] = "Article titled: '" + @news.subject + "'   successfully destroyed"
    @news.destroy
    redirect_to threads_path(:f => "news")
  end

  private
    def set_new
      @news = New.find(params[:id])
    end

    def news_params
      params.require(:new).permit(:subject, :article, :featured, :avatar, {pictures: []})
    end

end

app/views/news/news/show.html.erb
<div class="column-2">
  <div class="descriptor">
    <%= link_to "Forums", threads_path %> >
    <%= link_to "News", threads_path(:f => "news")%> >
    <span><%=@news.subject%></span>
  </div>
  <div class="news-article">
    <div class="article-title">
      <%=@news.subject%>
    </div>
    <div class="article-stuff">
      <div class="article-headshot">
      </div>
      <div class="article-info">
        <div class="article-author">
          <% if @news.user.nil? %>
            <div class="avatar"></div>
            <div>User Deleted</div>
          <% else %>
            <div class="avatar"><%=image_tag(@news.user.avatar) if @news.user.avatar.attached?%></div>
            <div><%=@news.user.username.capitalize%></div>
          <% end %>
        </div>
        <div class="article-date">Posted <%=time_ago_in_words(@news.created_at) + " ago"%></div>
      </div>
    </div>
    <div class="article-body">
      <%= sanitize @news.article %>
    </div>
  </div>

  <div class="descriptor">Comments</div>
  <%= render(partial: 'forums/forum_posts/post', collection: @news.forum_posts.includes(:user)) %>
  <div class="post-reply bottom-reply">
    <% if user_signed_in? %>
      <%= form_for(@post, url: news_posts_path(@news)) do |f| %>
        <%= f.cktext_area :body, ckeditor: {toolbar: "mini", height: 200, toolbarCanCollapse: true}, class: "ckeditor"%>
        <%= f.submit "Submit Post", class: "submit-post-button" %>
      <% end %>
    <% else %>
      Login or register to add your comment to the discussion.
    <% end %>
  </div>
  <% if policy(@news).destroy? %>
    <div class="descriptor">Moderator Actions</div>
    <div class="admin-actions">
      <%= link_to 'Delete Article', news_path(@news), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit Article', 'javascript:;', class: "admin-panel 1" %>
    </div>
    <div id="panel-1" class="admin-form hidden">
      <%= form_for(@news, url: news_path(@news), method: :patch) do |f| %>
        <div class='fields'>
          <div>
            <div class="descriptor">Title</div>
            <%= f.text_field :subject, :value => @news.subject %>
          </div>
          <div>
            <div class="descriptor">Content</div>
            <%= f.cktext_area :article, value: @news.article, ckeditor: {height: 300, toolbarCanCollapse: true}%>
          </div>
          <div>
            <div class="descriptor">Logo</div>
            <div class="edit-avatar">
              <div class="avatar"><%= image_tag(@news.avatar) if @news.avatar.attached?%></div>
              <div><%=@news.avatar.filename if @news.avatar.attached?%></div>
              <div><%= f.file_field :avatar%></div>
            </div>
          </div>
          <div>
              <div class="descriptor">Featured</div>
              <%= f.check_box :featured, :value => @news.featured %>
          </div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="column-4">
  <%= render "layouts/matches", :upcoming => @upcoming, :completed => @completed %>
</div>