config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: 'users' do
    resources :users, :path => 'u', :only => [:index, :show, :destroy]
  end

  def post_resource
    resources :forum_posts, :path => 'p', :as => 'posts'
  end

  scope module: 'forums' do
    resources :forum_threads, :path => 'forums', :as => 'threads' do
      post_resource
    end
    resources :forum_posts, :path => 'forums/p', :as => 'posts', :only => [] do
      member do
        post 'vote'
      end
      post_resource
    end
    resources :officials, :path => 'matches', :as => 'matches', :only => [] do
      post_resource
    end
    resources :news, :path => 'news', :as => 'news', :only => [] do
      post_resource
    end
  end

  scope module: 'news' do
    resources :news, :path => 'news', :as => 'news'
  end

  scope module: 'officials' do
    resources :events do
      resources :sections, :path => 's', :except => [:index]
    end
    resources :rankings, :only => [:index]
    resources :officials, :path => 'matches', :as => 'matches', :except => [:edit] do
      resources :maps, :only => [:create, :update, :destroy]
    end
    resources :teams
    resources :players
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
end

app/models/official/eventteam.rb
class Eventteam < ApplicationRecord
  belongs_to :event
  belongs_to :team
end

app/models/official/map.rb
class Official::Map < ApplicationRecord
  belongs_to :official
  belongs_to :winner, class_name: 'Team', foreign_key: 'winner_id', optional: true
  serialize :score
  validates :state, presence: true
end

app/models/official/official.rb
class Official < ApplicationRecord
  belongs_to :section
  belongs_to :event
  belongs_to :team1, class_name: 'Team', foreign_key: 'team1_id'
  belongs_to :team2, class_name: 'Team', foreign_key: 'team2_id'
  belongs_to :winner, class_name: 'Team', foreign_key: 'winner_id', optional: true
  before_save :callback_teams, if: :will_save_change_to_winner_id?
  after_create :default_maps
  after_create :give_title
  has_many :forum_posts, as: :commentable
  serialize :score
  has_many :maps
  has_many :performances, :through => :maps
  validates :start, presence: true
  validates :end, presence: true

  def self.h2hs(teams, id)
    team1, team2 = teams[0], teams[1]
    h2hs = Official.where(team1: team1, team2: team2).or(Official.where(team1: team2, team2: team1)).where.not(winner_id: nil, id: id).order(start: :desc).includes(:team1, :team2, section: :event)
    return reverse_matches(team1, h2hs)
  end

  def self.recents(teams, id)
    team1, team2 = teams[0], teams[1]
    team1_recents, team2_recents = recents_helper(team1, id), recents_helper(team2, id)
    return [team1_recents, team2_recents]
  end

  def self.recents_helper(team, id)
    recents = Official.where("(team1_id = ? OR team2_id = ?) AND id != ?", team.id, team.id, id).where.not(winner_id: nil).order(start: :desc).includes(team1: [pic_attachment: :blob], team2: [pic_attachment: :blob]).limit(5)
    return reverse_matches(team, recents)
  end

  def self.reverse_matches(team, recents)
    recents.each do |recent|
      if team != recent.team1
        recent.score.reverse!
        hello = recent.team1
        recent.team1 = recent.team2
        recent.team2 = hello
      end
    end
    return recents
  end

  def update_score(winner)
    if winner == self.team1.id
      self.score[0] += 1
    else
      self.score[1] += 1
    end
    self.save!
  end

  private

  def give_title
    title = self.team1.shortname + " vs " + self.team2.shortname + " - " + self.event.name + " " + self.section.name
    self.subject = title
    self.save!
  end

  def callback_teams
    winner = self.winner_id
    loser = ((self.team1_id == winner) ? self.team2_id : self.team1_id)
    Team.update_teams(winner, loser, self.end)
  end

  def default_maps
    if self.identifier.nil?
      for i in 0..(self.map_count-1)
        self.maps << Map.create(official_id: self.id, winner_id: nil, score: [0, 0], name: nil, state: "unfinished")
      end
    end
  end
end

app/models/official/team.rb
class Team1 < ApplicationRecord
  has_many :eventteams
  has_many :events, through: :eventteams
  has_many :players
  serialize :socials
  validates :name, presence: true
  validates :country, presence: true

  COUNTRIES = {'South Korea':'kr', 'United States': 'us', 'France': 'fr', 'United Kingdom': 'uk',
              'China': 'cn', 'Canada': 'ca', 'Russia': 'ru'}
end

app/controllers/officials/events_controller.rb
class Officials::EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy, :update]
  before_action :get_event_matches, except: [:index, :create, :update]

  def index
    @teams = Team.all
    @event = Event.new
    if params[:s] == 'completed'
      @events = Event.where("? > end_date", Date.current)
    else
      @events = Event.where("start_date <= ? AND end_date >= ?", Date.current, Date.current)
    end
  end

  def show
    @section = Section.new
    @regulars = []
    @event.sections.each {|stage|
       @regulars += stage.officials.where("match_type = ?", "regular").includes(:winner, :team1, :team2, maps: :winner)}
    @teams, @standings = Section.standings(@event.teams, @regulars)
  end

  def create
    @event = Event.new(event_params)
    authorize(@event)
    @event.check_teams(params[:teams])

    if @event.save
      flash[:success] = "Event successfully created."
      redirect_to event_path(@event)
    else
      flash[:danger] = @event.errors.full_messages
      redirect_to events_path
    end
  end

  def update
    authorize @event
    if @event.update_attributes(event_params.except(:teams))
      @event.check_teams(params[:teams])
      flash[:success] = "Event successfully updated."
    else
      flash[:danger] = "Event field caused an error."
    end
    redirect_to @event
  end

  def destroy
    authorize @event
    name = @event.name
    @event.destroy
    flash[:success] = "Event '#{name}' successfully deleted."
    redirect_to events_path
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :location, :country, :prize, :start_date, :end_date, :desc, :teams, :logo)
    end

    def get_event_matches
      @completed = Official.where(event_id: @event.id).where(start: (DateTime.now - 3.months)..(DateTime.now - 3.hours)).order(start: :desc).limit(5).includes(:team1, :team2, :event, :section)
      @upcoming = Official.where(event_id: @event.id).where(end: DateTime.now..(DateTime.now + 3.months)).limit(5).includes(:team1, :team2, :event, :section)
    end
end

app/controllers/officials/maps_controller.rb
class Officials::MapsController < ApplicationController
  before_action :set_map, except: [:create]

  def create
    @map = Map.new(map_params)
    (params[:score].nil? ? (@map.score = [0,0]) : (@map.score = params[:score].map{|num| num.to_i}))
    authorize @map
    if @map.save
      flash[:success] = "Successfully created a map"
    else
      flash[:danger] = @map.errors.full_messages
    end
    redirect_to match_path(@map.official)
  end

  def update
    authorize @map
    (params[:score].nil? ? (@map.score = [0,0]) : (@map.score = params[:score].map{|num| num.to_i}))
    @map.def_players(params[:players])
    if @map.update_attributes(map_params)
      flash[:success] = "Successfully updated map"
    else
      flash[:danger] = "Unable to update map, a field was input incorrectly"
    end
    redirect_to match_path(@map.official_id)
  end

  def destroy
    authorize @map
    match = @map.official
    flash[:success] = "Successfully deleted map"
    @map.destroy
    redirect_to match_path(match)
  end

  private
  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:official_id, :winner_id, :score, :name, :state, :performances)
  end
end

app/controllers/officials/officials_controller.rb
class Officials::OfficialsController < ApplicationController
  before_action :set_match, except: [:create, :index]

  def index
    if params[:f] == "comp"
      @officials = Official.where(start: (DateTime.now - 3.years)..(DateTime.now - 3.hours)).paginate(:page => params[:page]).order(start: :desc).includes(:team1, :team2, :event, :section)
    else
      @officials = Official.where(end: DateTime.now..(DateTime.now + 6.months)).paginate(:page => params[:page]).includes(:team1, :team2, :event, :section)
    end
  end

  def show
    @section, @teams = Section.find(@match.section_id), Team.find(@match.team1_id, @match.team2_id)
    @event, @maps = Event.find(@section.event_id), @match.maps
    @h2hs, @recents = Official.h2hs(@teams, @match.id), Official.recents(@teams, @match.id)
    @maps_json = Map.get_perfs(@maps, @teams)
    @forum_post = ForumPost.new
    @completed = Official.where(event_id: @event.id).where(start: (DateTime.now - 3.months)..(DateTime.now - 3.hours)).order(start: :desc).limit(5).includes(:team1, :team2, :event, :section)
    @upcoming = Official.where(event_id: @event.id).where(end: DateTime.now..(DateTime.now + 3.months)).limit(5).includes(:team1, :team2, :event, :section)
  end

  def create
    @match = Official.new(match_params)
    (params[:score].nil? ? (@match.score = [0,0]) : (@match.score = params[:score].map{|num| num.to_i}))
    authorize @match
    if @match.save
      flash[:success] = "Match successfully created."
      redirect_to match_path(@match)
    else
      flash[:danger] = @match.errors.full_messages
      redirect_to event_section_path(params[:official][:event_id], params[:official][:section_id])
    end
  end

  def update
    authorize @match
    (params[:score].nil? ? (@match.score = [0,0]) : (@match.score = params[:score].map{|num| num.to_i}))
    if @match.update_attributes(match_params)
      flash[:success] = "Match successfully updated."
    else
      flash[:danger] = "Unable to edit match. Field incorrectly inputted."
    end
    redirect_to match_path(@match)
  end

  def destroy
    authorize @match
    @event, @section = @match.event, @match.section
    flash[:success] = "Successfully destroyed match"
    @match.destroy
    redirect_to event_section_path(@event, @section)
  end

  private
    def set_match
      @match = Official.find(params[:id])
    end

    def match_params
      params.require(:official).permit(:team1_id, :team2_id, :winner_id, :identifier, :label, :score, :match_type, :map_count, :start, :end, :section_id, :event_id, :subject)
    end
end

app/controllers/officials/players_controller.rb
class Officials::PlayersController < ApplicationController
  before_action :set_player, only: [:show, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @teams = Team.all
    @player = Player.new
    @players = Player.includes(:team).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @teams = Team.all
    @player.past_teams.nil? ? @past_teams = [] : @past_teams = @player.past_teams.reverse.map {|team| Team.find(team)}
    @recent_matches = Official.joins(:performances => :map).where(:performances => {:player => @player}).distinct.order(start: :desc).paginate(:page => params[:page], :per_page => 20).includes(:team1, :team2, :event, :section)
  end

  def create
    @player = Player.new(player_params)
    authorize @player
    @player.socials = player_params[:socials]

    if @player.save
      flash[:success] = "Player successfully created"
      redirect_to @player
    else
      flash[:danger] = @player.errors.full_messages
      redirect_to players_path
    end
  end

  def update
    authorize @player
    if @player.update_attributes(player_params)
      flash[:success] = "Successfully updated Player"
    else
      flash[:danger] = "Unable to update Player. There is an error with a field."
    end
    redirect_to player_path(@player)
  end

  def destroy
    authorize @player
    @player.destroy
    flash[:success] = "Player successfully deleted."
    redirect_to players_path
  end

  private

    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:starter, :headshot, :eng_name, :nat_name, :nicknames, :handle, :country, :age, :roles, :team_id, :past_teams, socials: [:TWITTER, :DISCORD, :YOUTUBE_CHANNEL, :FACEBOOK, :INSTAGRAM, :TWITCH])
    end

  def sort_column
    Player.column_names.include?(params[:sort]) ? (column = params[:sort]) : (column = "LOWER(handle)")

    if !params[:sort].nil? && (params[:sort].include? ("."))
      column = params[:sort]
    end

    return column
  end

  def sort_direction
    %w[asc desc].include?(params[:d]) ? params[:d] : "asc"
  end

end

app/controllers/officials/rankings_controller.rb
class Officials::RankingsController < ApplicationController
  helper_method :sort_column, :sort_direction, :selected_event

  def index
    @events = Event.where(display_ranking: true)
    @primaries = selected_event.teams
    @default = @primaries.order(rating: :desc)
    @custom = @primaries.order(sort_column + " " + sort_direction)
  end

  private

  def sort_column
    Team.column_names.include?(params[:sort]) ? params[:sort] : "rating"
  end

  def sort_direction
    %w[asc desc].include?(params[:d]) ? params[:d] : "desc"
  end

  def selected_event
    queried_event = Event.find_by(shortname: params[:e])
    queried_event.nil? ? Event.find_by(primary_ranking: true) : queried_event
  end
end

app/controllers/officials/sections_controller.rb
class Officials::SectionsController < ApplicationController
  before_action :set_section, only: [:show, :destroy, :update]
  before_action :set_event

  def show
    @match = Official.new
    @sections = @event.sections
    @officials = @section.officials.includes(:team1, :team2)
    @regulars = @officials.where("match_type = ?", "regular").includes(:winner, maps: :winner)
    @teams, @standings = Section.standings(@event.teams, @regulars)
  end

  def create
    @section = Section.new(section_params)
    @section.event = @event
    authorize @section
    if @section.save
      flash[:success] = "Section successfully created."
      redirect_to event_section_path(@event, @section)
    else
      flash[:danger] = @section.errors.full_messages
      redirect_to event_path(@event)
    end
  end

  def update
    authorize @section
    if @section.update_attributes(section_params)
      flash[:success] = "Successfully updated section"
    else
      flash[:danger] = "Unable to update section."
    end
    redirect_to event_section_path(@event, @section)
  end

  def destroy
    authorize @section
    flash[:success] = "Successfully destroyed section"
    @section.destroy
    redirect_to event_path(@event)
  end

  private
    def set_section
      @section = Section.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def section_params
      params.require(:section).permit(:name, :start, :end)
    end
end

app/controllers/officials/teams_controller.rb
class Officials::TeamsController < ApplicationController
  before_action :set_team, only: [:show, :new, :destroy, :edit, :update]
  before_action :set_info, only: [:index, :create]

  def index
  end

  def show
    @players = @team.players
    @officials = Official.where("team1_id = ? OR team2_id = ?", @team.id, @team.id).includes(:team1, :team2, :event, :section).order(start: :desc).paginate(:page => params[:page], :per_page => 15)
    @info = [@officials.collect{|match| match.team1}, @officials.collect{|match| match.team2}, @officials.collect{|match| match.event}, @officials.collect{|match| match.section}]
  end

  def create
    @team = Team.new(team_params)
    authorize @team
    if params[:players]
      params[:players].each do |player|
        plyr = Player.find(player.to_i)
        unless @team.players.include?(plyr)
          @team.players << plyr
        end
      end
    end
    @team.socials = team_params[:socials]

    if @team.save
      flash[:success] = "Team successfully created."
      redirect_to @team
    else
      flash.now[:danger] = @team.errors.full_messages
      render 'index'
    end

  end

  def update
    authorize @team
    if @team.update_attributes(team_params)
      flash[:success] = "Successfully updated Team"
    else
      flash[:danger] = "Unable to update Team. There is an error with a field."
    end
    redirect_to team_path(@team)
  end

  def destroy
    authorize @team
    name = @team.name
    @team.destroy
    flash[:success] = "Team '#{name}' successfully deleted."
    redirect_to teams_path
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def set_info
      @players = Player.all.order('LOWER(handle)')
      @teams, @team = Team.all, Team.new
      @events = Event.all
    end

    def team_params
      params.require(:team).permit(:name, :shortname, :website, :logo, :country, :streak, :winnings, :rating, :games_played, :last_played, :players, socials: [:TWITTER, :DISCORD, :YOUTUBE_CHANNEL, :FACEBOOK, :INSTAGRAM, :TWITCH])
    end
end

app/views/officials/officials/index.html.erb
<div class="column-2 matches-column">
  <div class="descriptor">
    <span><%= link_to "Schedule", matches_path %></span>
    <span><%= link_to "Results", matches_path(:f => "comp")%></span>
  </div>

  <div class="matches-page shadow-sm">
    <% @officials.each do |match| %>
      <%= react_component("Match", {match: match, compact: false, teams: [match.team1, match.team2], event: match.event, section: match.section}, {:style => "margin: 1px 0;"}) %>
    <% end %>
  </div>

  <div class="pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false, :inner_window => 1, :outer_window => 1 %>
  </div>
</div>

app/views/officials/officials/show.html.erb
<div class="column-2 match-page">
  <div class="descriptor">Match Summary</div>
  <div class="shadow-sm match-header" style="border-top: 2px solid <%=@event.color%>">
    <div class="match-header-info">
      <div class="match-header-event">
        <div><%= link_to @event.name, event_path(@event), class: "link-nodec color"%></div>
        <div><%= @section.name %>: <%= @match.match_type.capitalize %></div>
      </div>
      <div class="match-header-date">
        <div><%= @match.start.strftime("%A, %B %d") %></div>
        <div><%= @match.start.localtime.strftime("%I:%M %p %Z")%></div>
      </div>
    </div>
    <div class="match-header-scoreboard">
      <%= link_to team_path(@teams[0]), class: "link-nodec color" do %>
        <div class="match-header-teams">
          <div><%= @teams[0].name %></div>
          <div><%= image_tag(@teams[0].pic, class: 'team-img-lg') if @teams[0].pic.attached?%></div>
        </div>
      <% end %>
      <div class="match-header-score">
        <div class="score-entrys">
          <span class="score-entry"><%= @match.score[0]%></span>
          <span class="score-entry"><%= @match.score[1]%></span>
        </div>
        <div>BO<%= @maps.size %></div>
      </div>
      <%= link_to team_path(@teams[1]), class: "link-nodec color" do %>
        <div class="match-header-teams">
          <div><%= image_tag(@teams[1].pic, class: 'team-img-lg') if @teams[1].pic.attached?%></div>
          <div><%= @teams[1].name %></div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="descriptor">Maps</div>
  <%= react_component("matchMaps", {maps_json: @maps_json, teams: @teams}) %>

  <div class="descriptor">Head to Head</div>
  <div class='shadow-sm match-head-to-head'>
    <div class="head-to-head-teams">
      <%= link_to team_path(@teams[0]), class: "link-nodec" do %>
        <div>
          <%= image_tag(@teams[0].pic, class: 'team-img-md') if @teams[0].pic.attached?%>
          <%= @teams[0].name %>
        </div>
      <% end %>
      <%= link_to team_path(@teams[1]), class: "link-nodec" do %>
        <div>
          <%= @teams[1].name %>
          <%= image_tag(@teams[1].pic, class: 'team-img-md') if @teams[1].pic.attached?%>
        </div>
      <% end %>
    </div>
    <div class="match-h2hs">
      <% if @h2hs.empty? %>
        <div style="text-align: center; padding: 1rem 0;">No previous encounters.</div>
      <% end %>
      <% @h2hs.each do |h2h|%>
        <%= link_to match_path(h2h), class: "link-nodec" do%>
          <div class="match-h2h">
            <div class="match-h2h-event">
              <div><%= image_tag("events/" + h2h.section.event.name.split(" ")[0,2].join("-")+ ".png",class:"event-logo")%></div>
              <div class="match-h2h-event-name"><%= h2h.section.event.name %>: <%= h2h.section.name %></div>
            </div>
            <div class="match-h2h-teams">
              <div class="checkmark">
                <% if h2h.score[0] > h2h.score[1] %>
                  <%= image_tag("misc/check-mark-3-32", class: 'check')%>
                <% end %>
              </div>
              <div>
                <%= image_tag(h2h.team1.pic, class: 'team-logo') if h2h.team1.pic.attached?%>
              </div>
              <div class="score-entrys">
                <span class="score-entry"><%= h2h.score[0]%></span>
                <span class="score-entry"><%= h2h.score[1]%></span>
              </div>
              <div>
                <%= image_tag(h2h.team2.pic, class: 'team-logo') if h2h.team2.pic.attached?%>
              </div>
              <div class="checkmark">
                <% if h2h.score[0] < h2h.score[1] %>
                  <%= image_tag("misc/check-mark-3-32", class: 'check')%>
                <% end %>
              </div>
            </div>
            <div class="match-h2h-date">
              <%=h2h.start.strftime("%m/%d/%Y")%>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="descriptor">Recent Matches</div>
  <div class="match-recent-matches">
    <% @recents.each_with_index do |team, index| %>
      <div class="shadow-sm match-recent-team">
        <% team.each do |match|%>
          <%= link_to match_path(match), class: 'link-nodec' do %>
            <div class="match-recent-entry <%= match.team1.id == match.winner_id ? 'match-win': 'match-lose'%>">
              <div class="match-recent-entry-score">
                <span class="score-entry"><%= match.score[0]%></span>
                <span class="score-entry"><%= match.score[1]%></span>
              </div>
              <div class="match-recent-entry-opp">
                <div><em>vs</em></div>
                <div>
                  <%=image_tag(match.team2.pic, class: 'team-logo') if match.team2.pic.attached?%>
                </div>
                <div><%= match.team2.name %></div>
              </div>
              <div class="match-recent-entry-date"><%= match.start.strftime("%m/%d/%Y")%></div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="descriptor">Comments</div>
  <%= render(partial: 'forums/forum_posts/post', collection: @match.forum_posts.includes(:user)) %>

  <div class="post-reply bottom-reply">
    <% if user_signed_in? %>
      <div class="post-reply-topbar"></div>
      <%= form_for(@forum_post, url: match_posts_path(@match)) do |f| %>
        <%= f.cktext_area :body, ckeditor: {toolbar: "mini", height: 200, toolbarCanCollapse: true}, class: "ckeditor"%>
        <%= f.submit "Submit Post", class: "submit-post-button" %>
      <% end %>
    <% else %>
      Login or register to add your comment to the discussion.
    <% end %>
  </div>
  <% if policy(@section).admin? %>
    <div class="descriptor">Admin Actions</div>
    <div class="admin-actions">
      <%= link_to 'Edit Match', 'javascript:;', class: "admin-panel 1" %>
      <%= link_to 'Delete Match', match_path(@match), method: :delete, data: { confirm: 'Are you sure?' }%>
      <%= link_to 'Edit Maps', 'javascript:;', class: "admin-panel 2" %>
      <%= link_to 'Add Map', 'javascript:;', class: "admin-panel 3" %>
    </div>
    <div id="panel-1" class="admin-form hidden">
      <%= form_for(@match, url: match_path(@match)) do |f| %>
        <div class='fields split'>
          <div>
            <div class="descriptor">Team 1</div>
            <%= f.select :team1_id, options_from_collection_for_select(@teams, 'id', 'name', @teams[0].id), :required => true, prompt: "" %>
          </div>
          <div>
            <div class="descriptor">Team 2</div>
            <%= f.select :team2_id, options_from_collection_for_select(@teams, 'id', 'name', @teams[1].id), :required => true, prompt: "" %>
          </div>
          <div>
            <div class="descriptor">Winner</div>
            <%= f.select :winner_id, options_from_collection_for_select(@teams, 'id', 'name'), :required => true, prompt: "" %>
          </div>
          <div>
            <div class="descriptor">Score</div>
            <%= number_field_tag "score[]",  0 %>
            <%= number_field_tag "score[]",  0 %>
          </div>
          <div>
            <div class="descriptor">Match Type</div>
            <%= f.text_field :match_type %>
          </div>
          <div>
            <div class="descriptor">Map Count</div>
            <%= f.number_field :map_count %>
          </div>
          <div>
            <div class="descriptor">Start</div>
            <%= f.datetime_field :start %>
          </div>
          <div>
            <div class="descriptor">End</div>
            <%= f.datetime_field :end %>
          </div>
          <div>
            <div class="descriptor">Event</div>
            <%= f.number_field :event_id, :value => @event.id, :readonly => true %>
          </div>
          <div>
            <div class="descriptor">Section</div>
            <%= f.number_field :section_id, :value => @section.id, :readonly => true %>
          </div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
    <div id="panel-2" class="admin-form hidden">
      <div class="fields">
        <div class="form-maps">
          <% @match.maps.each_with_index do |map, index| %>
            <div class="form-map">
              <div class="form-map-actions">
                <div class='form-map-num descriptor'><%= "Map #{index + 1}"%></div>
                <%= link_to "Delete" , match_map_path(@match, map), method: :delete, data: {confirm: 'Are you sure?'}%>
              </div>
              <div class="form-map-form">
                <%= form_for(map, url: match_map_path(@match, map)) do |a| %>
                  <div>
                    <div class="descriptor">Map Winner</div>
                    <%= a.select :winner_id, options_from_collection_for_select(@teams, 'id', 'name', map.winner_id), :required => true, prompt: "" %>
                  </div>
                  <div>
                    <div class="descriptor">Score</div>
                    <div>
                      <%=@teams[0].name%><%= number_field_tag "score[]",  map.score.to_a[0] %>
                      <%=@teams[1].name%><%= number_field_tag "score[]",  map.score.to_a[1] %>
                    </div>
                  </div>
                  <div>
                    <div class="descriptor">Name</div>
                    <%= a.text_field :name, value: map.name %>
                  </div>
                  <div>
                    <div class="descriptor">State</div>
                    <%= a.select :state, options_for_select(['finished', 'unfinished'], map.state), :required => true %>
                  </div>
                  <div>
                    <div class="descriptor">Players</div>
                    <%= a.fields_for :performances do |aa| %>
                      <%=@teams[0].name%>
                      <% map.team1_perfs.includes(:player).each do |perf| %>
                        <%= select_tag 'players[]', options_from_collection_for_select(@teams[0].players, 'id', 'handle', perf.player_id) %>
                      <% end %>
                      <%=@teams[1].name%>
                      <% map.team2_perfs.includes(:player).each do |perf| %>
                        <%= select_tag 'players[]', options_from_collection_for_select(@teams[1].players, 'id', 'handle', perf.player_id) %>
                      <% end %>
                    <% end %>
                  </div>
                  <%= a.submit "Submit"%>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div id="panel-3" class="admin-form hidden">
      <div class="fields">
        <div class="descriptor">Add a Map</div>
        <%= form_for(Map.new, url: match_maps_path(@match)) do |f| %>
          <%= f.hidden_field :official_id, :value => @match.id %>
          <div>
            <div class="descriptor">Winner</div>
            <%= f.select :winner_id, options_from_collection_for_select(@teams, 'id', 'name'), :required => true, prompt: "" %>
          </div>
          <div>
            <div class="descriptor">Score</div>
            <div><%=@teams[0].name%><%= number_field_tag "score[]",  0 %>
              <%= @teams[1].name%><%= number_field_tag "score[]",  0 %></div>
          </div>
          <div>
            <div class="descriptor">Name</div>
            <%= f.text_field :name, placeholder: "ex. Rialto" %>
          </div>
          <div>
            <div class="descriptor">State</div>
            <%= f.select :state, options_for_select(['finished', 'unfinished'], "unfinished"), :required => true %>
          </div>
          <%= f.submit "Submit" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="column-4">
  <%= render "layouts/matches", :upcoming => @upcoming, :completed => @completed %>
</div>